/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Administrador;

import BaseDatos.Conexion_Consultas;
import Clases.Actividad;
import Clases.Validaciones;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import BaseDatos.SQLActividades;
import javax.swing.ImageIcon;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Johnny
 */
public class ActividadesVtn extends javax.swing.JFrame {

    //Variables para mover la ventana  
    int mousex;
    int mousey;

    //Creamos una variable para darle un modelo a nuestra tabla 
    DefaultTableModel modeloTabla;

    String titulo[] = {"id", "Actividades"};
    String datos[][] = {};

    //Posicion de de la fila en la que dimos click  
    int posFila;
    //Posicion de la fila al editar  
    int filaEditar;

    //Para saber si le di click en editar 
    boolean editando = false;

    //Constructor para las validaciones 
    Validaciones valido = new Validaciones();

    //Variable que usare para saber si di click en la tabla  
    boolean btnAvilitados = false;

    //Creamos un array de actividad  
    ArrayList<Actividad> actividades = new ArrayList();

    ArrayList<Actividad> actividadesF = new ArrayList();

    //Actividad copia nombre  
    String nombre_copia;

    public ActividadesVtn() {
        initComponents();
        
         //Icono de la palicacion 
                try {
            setIconImage(new ImageIcon(getClass().getResource("../img/LogoKayranaCircularV.1.png")).getImage());
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }

        //Le pasamos el modelo a nuestra tabla 
        modeloTabla = new DefaultTableModel(datos, titulo);

        //Nos conectamos a base de datos  
        Conexion_Consultas.conectar();

        actualizarTabla();

        tblActividades.setModel(modeloTabla);

        TableColumnModel columna = tblActividades.getColumnModel();

        Similitudes.ocultarID(tblActividades);

        columna.getColumn(1).setPreferredWidth(200);

        //Modificamos el Header de nuestra tabla  
        Similitudes.tituloTbls(tblActividades);

        //Ocultamos todos los errores 
        lblErrorMateria.setVisible(false);
        lblErrorNuevaMateria.setVisible(false);

        //Deasbilitamos los botones  
        Similitudes.btnsModoInactivo(btnEditar, btnEliminar);
    }

    private void actualizarTabla() {
        //False son todas las actividades sin ningun filtro 
        actividades = SQLActividades.cargarActividades(false);
        //True solo trae las actividades que no esten eliminadas 
        actividadesF = SQLActividades.cargarActividades(true);

        if (actividadesF.size() > 0) {
            modeloTabla.setRowCount(0);

            for (int i = 0; i < actividadesF.size(); i++) {
                Object valores[] = {actividadesF.get(i).getId_actividad(),
                    actividadesF.get(i).getNombre_actividad()};
                modeloTabla.addRow(valores);
            }
        }
    }

    public boolean nuevaActividad(String materia) {
        boolean datosNuevos = true;
        String materiaComparar;

        try {
            for (int i = 0; i < actividades.size(); i++) {
                materiaComparar = actividades.get(i).getNombre_actividad();

                if (materia.equalsIgnoreCase(materiaComparar)) {
                    SQLActividades.eliminarActividad(actividades.get(i).getId_actividad(), false);
                    datosNuevos = false;
                    actualizarTabla(); 
                    break;
                }
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }

        return datosNuevos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividades = new JTable(){
            @Override 
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false; 
            }
        };
        lblErrorMateria = new javax.swing.JLabel();
        txtActividades = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblErrorNuevaMateria = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 235, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(231, 235, 230));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblActividades.setBackground(new java.awt.Color(231, 235, 230));
        tblActividades.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Actividad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblActividades.setSelectionBackground(new java.awt.Color(21, 89, 110));
        tblActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblActividadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblActividades);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 360, 330));

        lblErrorMateria.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblErrorMateria.setForeground(new java.awt.Color(173, 46, 25));
        lblErrorMateria.setText("Solo debe ingresar letras.");
        jPanel1.add(lblErrorMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 300, 20));

        txtActividades.setBackground(new java.awt.Color(51, 51, 51));
        txtActividades.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtActividades.setOpaque(false);
        jPanel1.add(txtActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 360, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 89, 110));
        jLabel2.setText("Actividad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        lblErrorNuevaMateria.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblErrorNuevaMateria.setForeground(new java.awt.Color(173, 46, 25));
        lblErrorNuevaMateria.setText("Ya ingreso esta actividad. ");
        jPanel1.add(lblErrorNuevaMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 190, 30));

        btnEliminar.setBackground(new java.awt.Color(118, 125, 127));
        btnEliminar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setOpaque(true);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 110, -1));

        btnGuardar.setBackground(new java.awt.Color(99, 144, 158));
        btnGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 110, -1));

        btnEditar.setBackground(new java.awt.Color(118, 125, 127));
        btnEditar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setFocusPainted(false);
        btnEditar.setOpaque(true);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/FondoLapiz3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 810, 460));

        jPanel2.setBackground(new java.awt.Color(9, 28, 32));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Login_26px_1.png"))); // NOI18N
        btnMenu.setToolTipText("Volver al menu");
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusPainted(false);
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMenu.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Login_26px_2.png"))); // NOI18N
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresar Actividades");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/BanerKay.png"))); // NOI18N
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblActividadesMouseClicked
        try {
            posFila = tblActividades.getSelectedRow();

            //Activamos nuestros botones
            if (posFila >= 0) {
                btnAvilitados = Similitudes.btnsModoActivo(btnEditar, btnEliminar);
            }
        } catch (IndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_tblActividadesMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {

            if (posFila >= 0 && btnAvilitados) {
                SQLActividades.eliminarActividad(Integer.parseInt(tblActividades.getValueAt(posFila, 0).toString()), true);
                
                modeloTabla.removeRow(posFila); 
            }

            //Cambiamos los botones a inactivos
            btnAvilitados = Similitudes.btnsModoInactivo(btnEditar, btnEliminar);
            editando = false;

        } catch (IndexOutOfBoundsException e) {
            System.out.println("Error al eliminar actividad: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        if (btnAvilitados) {
            Similitudes.btnEntered(btnEliminar);
        }
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        if (btnAvilitados) {
            Similitudes.btnExited(btnEliminar);
        }
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        boolean guardar = true;

        int id_actividad = 0;
        if (actividades.size() > 0) {
            id_actividad = actividades.get(actividades.size() - 1).getId_actividad();
        }

        id_actividad++;

        String actividad = txtActividades.getText();
        if (!valido.esLetras(actividad)) {
            lblErrorMateria.setVisible(true);
            guardar = false;
        } else if (!nuevaActividad(actividad)) {
            lblErrorNuevaMateria.setVisible(true);
            guardar = false;
        }

        if (guardar) {

            if (!editando) {
                Actividad act = new Actividad();
                act.setId_actividad(id_actividad);
                act.setNombre_actividad(actividad);
                act.setActividad_elim(false);

                SQLActividades.insertarActividad(act);
            }

            if (editando) {
                modeloTabla.setValueAt(actividad, filaEditar, 1);

                Actividad act = new Actividad();
                act.setId_actividad(Integer.parseInt(tblActividades.getValueAt(posFila, 0).toString()));
                act.setNombre_actividad(actividad);
                act.setActividad_elim(false);

                SQLActividades.editarActividad(act);

                editando = false;
            }

            txtActividades.setText("");

            btnAvilitados = Similitudes.btnsModoInactivo(btnEditar, btnEliminar);

            //Actualizamos nuestra tabla 
            actualizarTabla();

            //Ocultanos nuevamente los errores
            lblErrorMateria.setVisible(false);
            lblErrorNuevaMateria.setVisible(false);
        }

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        Similitudes.btnEntered(btnGuardar);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        Similitudes.btnExited(btnGuardar);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        try {
            if (posFila >= 0 && btnAvilitados) {
                filaEditar = posFila;

                txtActividades.setText(tblActividades.getValueAt(posFila, 1).toString());

                //Si selecionamos editar deasvilitamos los botones editar y eliminar
                btnAvilitados = Similitudes.btnsModoInactivo(btnEditar, btnEliminar);

                editando = true;
            }
        } catch (IndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        if (btnAvilitados) {
            Similitudes.btnEntered(btnEditar);
        }
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        if (btnAvilitados) {
            Similitudes.btnExited(btnEditar);
        }
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        AdministracionVtn admin = new AdministracionVtn();
        admin.setVisible(true);
        this.dispose();

        Conexion_Consultas.cerrarConexion();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActividadesVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActividadesVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActividadesVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActividadesVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActividadesVtn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorMateria;
    private javax.swing.JLabel lblErrorNuevaMateria;
    private javax.swing.JTable tblActividades;
    private javax.swing.JTextField txtActividades;
    // End of variables declaration//GEN-END:variables
}
