/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Administrador;

import Interfaz.Consultas.Consultas;
import Interfaz.LoginRegistro.Login;
import java.awt.Frame;
import javax.swing.ImageIcon;

/**
 *
 * @author Johnny
 */
public class AdministracionVtn extends javax.swing.JFrame {


    private int mousex; 
    private int mousey; 
    
    public AdministracionVtn() {
        initComponents();
        
        
         //Icono de la palicacion 
                try {
            setIconImage(new ImageIcon(getClass().getResource("../img/LogoKayranaCircularV.1.png")).getImage());
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuerpo = new javax.swing.JPanel();
        btnDocentes = new javax.swing.JButton();
        btnCarreras = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnJornadas = new javax.swing.JButton();
        btnPeriodoLectivo = new javax.swing.JButton();
        btnDistributivo = new javax.swing.JButton();
        btnActividades = new javax.swing.JButton();
        btnDistributivo1 = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JButton();
        btnVolverLogin = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCuerpo.setBackground(new java.awt.Color(21, 89, 110));
        panelCuerpo.setMinimumSize(new java.awt.Dimension(1100, 650));
        panelCuerpo.setPreferredSize(new java.awt.Dimension(1100, 650));
        panelCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDocentes.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDocentes.setForeground(new java.awt.Color(255, 255, 255));
        btnDocentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Add_User_Male_104px_1.png"))); // NOI18N
        btnDocentes.setText("Docentes");
        btnDocentes.setBorderPainted(false);
        btnDocentes.setContentAreaFilled(false);
        btnDocentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocentes.setFocusPainted(false);
        btnDocentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDocentes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Add_User_Male_104px.png"))); // NOI18N
        btnDocentes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocentesMouseClicked(evt);
            }
        });
        panelCuerpo.add(btnDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 160, 150));

        btnCarreras.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCarreras.setForeground(new java.awt.Color(255, 255, 255));
        btnCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Graduation_Cap_104px_1.png"))); // NOI18N
        btnCarreras.setText("Carreras");
        btnCarreras.setBorderPainted(false);
        btnCarreras.setContentAreaFilled(false);
        btnCarreras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarreras.setFocusPainted(false);
        btnCarreras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarreras.setIconTextGap(0);
        btnCarreras.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCarreras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Graduation_Cap_104px_3.png"))); // NOI18N
        btnCarreras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarrerasMouseClicked(evt);
            }
        });
        panelCuerpo.add(btnCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 150));

        btnMaterias.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnMaterias.setForeground(new java.awt.Color(255, 255, 255));
        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_School_104px.png"))); // NOI18N
        btnMaterias.setText("Materias");
        btnMaterias.setBorderPainted(false);
        btnMaterias.setContentAreaFilled(false);
        btnMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaterias.setFocusPainted(false);
        btnMaterias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaterias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_School_104px_1.png"))); // NOI18N
        btnMaterias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMateriasMouseClicked(evt);
            }
        });
        panelCuerpo.add(btnMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 160, 150));

        btnJornadas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnJornadas.setForeground(new java.awt.Color(255, 255, 255));
        btnJornadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Time_Span_104px_1.png"))); // NOI18N
        btnJornadas.setText("Jornadas");
        btnJornadas.setBorderPainted(false);
        btnJornadas.setContentAreaFilled(false);
        btnJornadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJornadas.setFocusPainted(false);
        btnJornadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJornadas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Time_Span_104px.png"))); // NOI18N
        btnJornadas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJornadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJornadasMouseClicked(evt);
            }
        });
        panelCuerpo.add(btnJornadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, 150));

        btnPeriodoLectivo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnPeriodoLectivo.setForeground(new java.awt.Color(255, 255, 255));
        btnPeriodoLectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Schedule_104px.png"))); // NOI18N
        btnPeriodoLectivo.setText("<html> Periodo <br> <center> Lectivo </center> </html>");
        btnPeriodoLectivo.setBorderPainted(false);
        btnPeriodoLectivo.setContentAreaFilled(false);
        btnPeriodoLectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeriodoLectivo.setFocusPainted(false);
        btnPeriodoLectivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeriodoLectivo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Schedule_104px_1.png"))); // NOI18N
        btnPeriodoLectivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeriodoLectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeriodoLectivoMouseClicked(evt);
            }
        });
        panelCuerpo.add(btnPeriodoLectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 160, 150));

        btnDistributivo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDistributivo.setForeground(new java.awt.Color(255, 255, 255));
        btnDistributivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Classroom_104px_1.png"))); // NOI18N
        btnDistributivo.setText("Paralelos");
        btnDistributivo.setBorderPainted(false);
        btnDistributivo.setContentAreaFilled(false);
        btnDistributivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDistributivo.setFocusPainted(false);
        btnDistributivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDistributivo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Classroom_104px_2.png"))); // NOI18N
        btnDistributivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDistributivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDistributivoMouseClicked(evt);
            }
        });
        panelCuerpo.add(btnDistributivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 160, 150));

        btnActividades.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Activity_Feed_104px.png"))); // NOI18N
        btnActividades.setText("Actividades");
        btnActividades.setBorderPainted(false);
        btnActividades.setContentAreaFilled(false);
        btnActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActividades.setFocusPainted(false);
        btnActividades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActividades.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Activity_Feed_104px_1.png"))); // NOI18N
        btnActividades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActividadesMouseClicked(evt);
            }
        });
        panelCuerpo.add(btnActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 160, 150));

        btnDistributivo1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDistributivo1.setForeground(new java.awt.Color(255, 255, 255));
        btnDistributivo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Week_View_104px.png"))); // NOI18N
        btnDistributivo1.setText("Distributivo");
        btnDistributivo1.setBorderPainted(false);
        btnDistributivo1.setContentAreaFilled(false);
        btnDistributivo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDistributivo1.setFocusPainted(false);
        btnDistributivo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDistributivo1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Week_View_104px_1.png"))); // NOI18N
        btnDistributivo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDistributivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDistributivo1MouseClicked(evt);
            }
        });
        panelCuerpo.add(btnDistributivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 160, 150));

        btnConsultas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Database_104px_1.png"))); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.setBorderPainted(false);
        btnConsultas.setContentAreaFilled(false);
        btnConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultas.setFocusPainted(false);
        btnConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Database_104px_2.png"))); // NOI18N
        btnConsultas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultasMouseClicked(evt);
            }
        });
        panelCuerpo.add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 160, 150));

        getContentPane().add(panelCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 810, 400));

        panelHeader.setBackground(new java.awt.Color(9, 28, 32));
        panelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelHeaderMouseDragged(evt);
            }
        });
        panelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelHeaderMousePressed(evt);
            }
        });
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kayrana");
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administracion del Sistema");
        panelHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnMinimizar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Minimize_Window_26px_4.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Minimize_Window_26px_5.png"))); // NOI18N
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        panelHeader.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 40, 40));

        btnVolverLogin.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnVolverLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Login_26px_1.png"))); // NOI18N
        btnVolverLogin.setText("Volver al Login");
        btnVolverLogin.setBorderPainted(false);
        btnVolverLogin.setContentAreaFilled(false);
        btnVolverLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverLogin.setFocusPainted(false);
        btnVolverLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Login_26px.png"))); // NOI18N
        btnVolverLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverLoginMouseClicked(evt);
            }
        });
        panelHeader.add(btnVolverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        btnCerrar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Close_Window_26px_7.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusPainted(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Close_Window_26px_5.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        panelHeader.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 0, 40, 40));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void panelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMousePressed
        mousex  = evt.getX(); 
        mousey = evt.getY(); 
    }//GEN-LAST:event_panelHeaderMousePressed


    
    private void panelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen(); 
        
        this.setLocation(x-mousex, y - mousey);     
    }//GEN-LAST:event_panelHeaderMouseDragged

    private void btnVolverLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverLoginMouseClicked
        Login login = new Login(); 
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverLoginMouseClicked

    private void btnCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarrerasMouseClicked
        CarrerasVtn carrera  = new CarrerasVtn(); 
        carrera.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCarrerasMouseClicked

    private void btnMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMateriasMouseClicked
        MateriasVtn materia = new MateriasVtn(); 
        materia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMateriasMouseClicked

    private void btnJornadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJornadasMouseClicked
        JornadasVtn jornada = new JornadasVtn(); 
        jornada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJornadasMouseClicked

    private void btnActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseClicked
        ActividadesVtn actividad = new ActividadesVtn(); 
        actividad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActividadesMouseClicked

    private void btnPeriodoLectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeriodoLectivoMouseClicked
        PeriodoLectivoVtn perLectivo = new PeriodoLectivoVtn(); 
        perLectivo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPeriodoLectivoMouseClicked

    private void btnDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocentesMouseClicked
        DocentesVtn docente = new DocentesVtn();  
        docente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDocentesMouseClicked

    private void btnDistributivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDistributivoMouseClicked
        ParalelosVtn paralelo = new ParalelosVtn(); 
        paralelo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDistributivoMouseClicked

    private void btnDistributivo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDistributivo1MouseClicked
        DistributivoVtn distributivo = new DistributivoVtn(); 
        distributivo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDistributivo1MouseClicked

    private void btnConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasMouseClicked
        Consultas consul = new Consultas(); 
        consul.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionVtn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividades;
    private javax.swing.JButton btnCarreras;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnDistributivo;
    private javax.swing.JButton btnDistributivo1;
    private javax.swing.JButton btnDocentes;
    private javax.swing.JButton btnJornadas;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnPeriodoLectivo;
    private javax.swing.JButton btnVolverLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables
}
