package Interfaz.Administrador;

import BaseDatos.Conexion_Consultas;
import BaseDatos.SQLCarreras;
import BaseDatos.SQLDistributivo;
import BaseDatos.SQLPeriodoLectivo;
import Clases.Carrera;
import Clases.Carrera_Jornada;
import Clases.Periodo_Lectivo;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Johnny
 */
public class DistributivoVtn extends javax.swing.JFrame {

    int mousex;
    int mousey;

    //Aqui gaurdare mis periodos lectivos 
    ArrayList<Periodo_Lectivo> periodos = new ArrayList();

    //Aqui guardamos las carreras de un isntituto  
    ArrayList<Carrera> carrerasDB = new ArrayList();

    //Aqui guarddamos el periodo lectivo selecionado  
    Periodo_Lectivo peri;

    String matrizClases[][];

    //Modelo de la tabla 
    DefaultTableModel modeloTabla;

    String titulo[] = {"cedula", "fk_materia", "Nombre docente", "Nombre Materia", "Horas Materia"};
    String datos[][] = {};

    public DistributivoVtn() {
        initComponents();
        Conexion_Consultas.conectar();

        //Icono de la palicacion 
        try {
            setIconImage(new ImageIcon(getClass().getResource("../img/LogoKayranaCircularV.1.png")).getImage());
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }

        //Le pasamos el modelo a nuestra tabla 
        modeloTabla = new DefaultTableModel(datos, titulo);

        tblInfoMat.setModel(modeloTabla);

        carrerasDB = SQLCarreras.cargarCarrerasDB(true);

        actualizarComboPeriLect();
    }

    private void actualizarComboPeriLect() {
        periodos = SQLPeriodoLectivo.cargarPeriodosLectivos(true);

        comboPeriodoLect.removeAllItems();

        for (int i = 0; i < periodos.size(); i++) {
            comboPeriodoLect.addItem(nomCarrera(periodos.get(i).getFk_carrera()) + " | "
                    + periodos.get(i).getFecha_ini_per_lect() + " - "
                    + periodos.get(i).getFecha_fin_epr_lect());
        }
    }

    private String nomCarrera(int fk_carrera) {
        String nombre = "";
        for (int i = 0; i < carrerasDB.size(); i++) {
            if (carrerasDB.get(i).getId_carrera() == fk_carrera) {
                nombre = carrerasDB.get(i).getNombre_Carrera();
                break;
            }
        }
        return nombre;
    }

    private Carrera buscarCarrera(int fk_carrera) {
        Carrera carrera = null;
        for (int i = 0; i < carrerasDB.size(); i++) {
            if (carrerasDB.get(i).getId_carrera() == fk_carrera) {
                carrera = carrerasDB.get(i);
                break;
            }
        }
        return carrera;
    }

    //Debemos enviar el formato asi Lunes/Viernes
    private int numDiasClase(String dias) {
        int pos = dias.indexOf("-");
        int numDC = 0;

        String diaIni = dias.substring(0, pos);
        String diaFin = dias.substring(pos + 1, dias.length());
        int ini = numDia(diaIni);
        int fin = numDia(diaFin);

        System.out.println("Dia inicio " + diaIni + "  Dia fin: " + diaFin);
        System.out.println("Num diaIni " + ini + "  Num diaFin " + fin);
        if (ini > 0) {
            ini -= 1;
            numDC = fin - ini;
        }

        return numDC;
    }

    private int numDia(String dia) {
        int num = 0;
        dia = dia.toLowerCase();

        switch (dia) {
            case "lunes":
                num = 1;
                break;
            case "martes":
                num = 2;
                break;
            case "miercoles":
                num = 3;
                break;
            case "jueves":
                num = 4;
                break;
            case "viernes":
                num = 5;
                break;
            case "sabado":
                num = 6;
                break;
            case "domingo":
                num = 7;
                break;
        }
        return num;
    }

    private void agregarFila(int fila, int colum) {

        matrizClases = new String[fila][colum];
        System.out.println("Vamos a imprimir nuestra matriz creada");

        for (int i = 0; i < matrizClases.length; i++) {
            for (int j = 0; j < matrizClases[i].length; j++) {
                System.out.print(matrizClases[i][j] + " ");
            }
            System.out.println("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        comboPeriodoLect = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        panelCuerpo = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        lblNumDiasSinFS2 = new javax.swing.JLabel();
        lblNumDias = new javax.swing.JLabel();
        lblNumSemanas2 = new javax.swing.JLabel();
        lblNumDias1 = new javax.swing.JLabel();
        lblNumSemanas = new javax.swing.JLabel();
        lblNumDiasSinFS = new javax.swing.JLabel();
        lblNumDiasSinFS3 = new javax.swing.JLabel();
        lblNumDiasSinFS4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblMateriasCarrera = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblMateriasCarreraDocente = new javax.swing.JLabel();
        panelParalelos = new javax.swing.JPanel();
        lblNumDiasSinFS5 = new javax.swing.JLabel();
        comboCiclos = new javax.swing.JComboBox<>();
        lblNumDiasSinFS6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblParalelosCiclo = new javax.swing.JLabel();
        lblNumDiasSinFS7 = new javax.swing.JLabel();
        comboJornadas = new javax.swing.JComboBox<>();
        lblParlJornadaCiclo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblParalelosCarrera = new javax.swing.JLabel();
        btnClasificarMat = new javax.swing.JButton();
        panelMasInfo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblInfoMat = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        panelHeader1 = new javax.swing.JPanel();
        btnMenu1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        btnParalelos = new javax.swing.JButton();
        btnMasInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(231, 235, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboPeriodoLect.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        comboPeriodoLect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPeriodoLectActionPerformed(evt);
            }
        });
        jPanel2.add(comboPeriodoLect, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 520, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 110, 172));
        jLabel7.setText("Seleccionar periodo lectivo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 30));

        panelCuerpo.setLayout(new java.awt.CardLayout());

        panelInfo.setBackground(new java.awt.Color(231, 235, 230));
        panelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumDiasSinFS2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNumDiasSinFS2.setForeground(new java.awt.Color(20, 110, 172));
        lblNumDiasSinFS2.setText("Docentes que dan materias de esta carrera");
        panelInfo.add(lblNumDiasSinFS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 400, 30));

        lblNumDias.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblNumDias.setForeground(new java.awt.Color(97, 45, 51));
        lblNumDias.setText("0");
        panelInfo.add(lblNumDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 180, 30));

        lblNumSemanas2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblNumSemanas2.setForeground(new java.awt.Color(20, 110, 172));
        lblNumSemanas2.setText("Numero de semanas: ");
        panelInfo.add(lblNumSemanas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 250, 30));

        lblNumDias1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblNumDias1.setForeground(new java.awt.Color(20, 110, 172));
        lblNumDias1.setText("Numero de dias: ");
        panelInfo.add(lblNumDias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 30));

        lblNumSemanas.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblNumSemanas.setForeground(new java.awt.Color(97, 45, 51));
        lblNumSemanas.setText("0");
        panelInfo.add(lblNumSemanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 150, 30));

        lblNumDiasSinFS.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblNumDiasSinFS.setForeground(new java.awt.Color(97, 45, 51));
        lblNumDiasSinFS.setText("0");
        panelInfo.add(lblNumDiasSinFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 170, -1));

        lblNumDiasSinFS3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblNumDiasSinFS3.setForeground(new java.awt.Color(20, 110, 172));
        lblNumDiasSinFS3.setText("Numero de dias sin fines de semana: ");
        panelInfo.add(lblNumDiasSinFS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 30));

        lblNumDiasSinFS4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNumDiasSinFS4.setForeground(new java.awt.Color(20, 110, 172));
        lblNumDiasSinFS4.setText("Materias de esta carrera");
        panelInfo.add(lblNumDiasSinFS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 30));
        panelInfo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 810, 10));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("<html> <center> Esto es otro nivel <br> GG </center> </html>");
        panelInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 100, 40));

        lblMateriasCarrera.setBackground(new java.awt.Color(231, 235, 230));
        lblMateriasCarrera.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMateriasCarrera.setText("jLabel1");
        lblMateriasCarrera.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMateriasCarrera.setOpaque(true);
        jScrollPane2.setViewportView(lblMateriasCarrera);

        panelInfo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, 280));

        lblMateriasCarreraDocente.setBackground(new java.awt.Color(231, 235, 230));
        lblMateriasCarreraDocente.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMateriasCarreraDocente.setText("jLabel1");
        lblMateriasCarreraDocente.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMateriasCarreraDocente.setOpaque(true);
        jScrollPane3.setViewportView(lblMateriasCarreraDocente);

        panelInfo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 420, 250));

        panelCuerpo.add(panelInfo, "card2");

        panelParalelos.setBackground(new java.awt.Color(231, 235, 230));
        panelParalelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumDiasSinFS5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNumDiasSinFS5.setForeground(new java.awt.Color(20, 110, 172));
        lblNumDiasSinFS5.setText("Selecione una Jornada:");
        panelParalelos.add(lblNumDiasSinFS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 220, 30));

        comboCiclos.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        comboCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCiclosActionPerformed(evt);
            }
        });
        panelParalelos.add(comboCiclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 50, 30));

        lblNumDiasSinFS6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNumDiasSinFS6.setForeground(new java.awt.Color(20, 110, 172));
        lblNumDiasSinFS6.setText("Paralelos de esta carrera");
        panelParalelos.add(lblNumDiasSinFS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelParalelos.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 20, 400));

        lblParalelosCiclo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblParalelosCiclo.setText("jLabel1");
        lblParalelosCiclo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelParalelos.add(lblParalelosCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 240, 340));

        lblNumDiasSinFS7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNumDiasSinFS7.setForeground(new java.awt.Color(20, 110, 172));
        lblNumDiasSinFS7.setText("Selecione un ciclo:");
        panelParalelos.add(lblNumDiasSinFS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 170, 30));

        comboJornadas.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        comboJornadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutina", "Vespertina" }));
        comboJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJornadasActionPerformed(evt);
            }
        });
        panelParalelos.add(comboJornadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 190, 30));

        lblParlJornadaCiclo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblParlJornadaCiclo.setText("jLabel1");
        lblParlJornadaCiclo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelParalelos.add(lblParlJornadaCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 230, 100));

        lblParalelosCarrera.setBackground(new java.awt.Color(231, 235, 230));
        lblParalelosCarrera.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblParalelosCarrera.setText("jLabel1");
        lblParalelosCarrera.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblParalelosCarrera.setOpaque(true);
        jScrollPane1.setViewportView(lblParalelosCarrera);

        panelParalelos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 350));

        btnClasificarMat.setText("Clasificar Materias");
        btnClasificarMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClasificarMatMouseClicked(evt);
            }
        });
        panelParalelos.add(btnClasificarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        panelCuerpo.add(panelParalelos, "card3");

        panelMasInfo.setBackground(new java.awt.Color(231, 235, 230));
        panelMasInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInfoMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblInfoMat);

        panelMasInfo.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 380));

        panelCuerpo.add(panelMasInfo, "card4");
        panelCuerpo.add(jPanel1, "card5");

        jPanel2.add(panelCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 810, 400));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 810, 450));

        panelHeader1.setBackground(new java.awt.Color(9, 28, 32));
        panelHeader1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelHeader1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelHeader1MouseDragged(evt);
            }
        });
        panelHeader1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelHeader1MousePressed(evt);
            }
        });
        panelHeader1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Login_26px_1.png"))); // NOI18N
        btnMenu1.setToolTipText("Volver al menu");
        btnMenu1.setBorderPainted(false);
        btnMenu1.setContentAreaFilled(false);
        btnMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu1.setFocusPainted(false);
        btnMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMenu1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMenu1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Login_26px_2.png"))); // NOI18N
        btnMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenu1MouseClicked(evt);
            }
        });
        panelHeader1.add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Distributivo");
        panelHeader1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 50));

        btnInfo.setText("Info");
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInfoMouseClicked(evt);
            }
        });
        panelHeader1.add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        btnParalelos.setText("Paralelos");
        btnParalelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnParalelosMouseClicked(evt);
            }
        });
        panelHeader1.add(btnParalelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        btnMasInfo.setText("Mas Info");
        btnMasInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasInfoMouseClicked(evt);
            }
        });
        panelHeader1.add(btnMasInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        getContentPane().add(panelHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MouseClicked
        AdministracionVtn admin = new AdministracionVtn();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenu1MouseClicked

    private void panelHeader1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeader1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_panelHeader1MouseDragged

    private void panelHeader1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeader1MousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_panelHeader1MousePressed

    ArrayList<String> cedulasDocen;


    private void comboPeriodoLectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPeriodoLectActionPerformed

        int pos = comboPeriodoLect.getSelectedIndex();
        System.out.println("Esta es la posicion " + pos);

        peri = periodos.get(pos);

        String diaIni = peri.getFecha_ini_per_lect().substring(0, 2);
        String mesIni = peri.getFecha_ini_per_lect().substring(3, 5);
        String anioIni = peri.getFecha_ini_per_lect().substring(6, 10);

        System.out.println("El dia que inicia " + diaIni);
        System.out.println("El mes que inicia " + mesIni);
        System.out.println("El año que inicia " + anioIni);

        String diaFin = peri.getFecha_fin_epr_lect().substring(0, 2);
        String mesFin = peri.getFecha_fin_epr_lect().substring(3, 5);
        String anioFin = peri.getFecha_fin_epr_lect().substring(6, 10);

        System.out.println("El dia que termina " + diaFin);
        System.out.println("El mes que termina " + mesFin);
        System.out.println("El año que termina " + anioFin);

        DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);

        Date fechaInicial = new Date();
        Date fechaFinal = new Date();

        try {
            fechaInicial = df.parse(peri.getFecha_ini_per_lect());
            System.out.println(fechaInicial);
        } catch (ParseException ex) {
            Logger.getLogger(DistributivoVtn.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception e){
            System.out.println("Hola fecha");
        }

        try {
            fechaFinal = df.parse(peri.getFecha_fin_epr_lect());
            System.out.println(fechaFinal);
        } catch (ParseException ex) {
            Logger.getLogger(DistributivoVtn.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception e){
            System.out.println("Hola fecha");
        }


        long tiempoFI = fechaInicial.getTime();
        long tiempoFF = fechaFinal.getTime();

        long tiempoPasado = tiempoFF - tiempoFI;

        long dias = tiempoPasado / (3600 * 24 * 1000);

        int diasPa = (int) dias;

        int semanasPa = diasPa / 7;

        int diasSinFS = diasPa - semanasPa * 2;

        System.out.println("Estos dias pasaron " + diasPa);

        lblNumDias.setText(diasPa + "");

        System.out.println("Semanas que pasaron " + semanasPa);

        lblNumSemanas.setText(semanasPa + "");

        System.out.println("Dias sin fin de semana " + diasSinFS);

        lblNumDiasSinFS.setText(diasSinFS + "");

        //Cargamos las materias de una carrera  
        ArrayList<ArrayList<String>> materiasCarrera = SQLDistributivo.cargarMateriasCarrera(peri.getFk_carrera());

        String ini = "<html> ";
        String fin = "</html>";
        String matCar = ini;
        String matDocCar = ini;

        for (int i = 0; i < materiasCarrera.size(); i++) {
            for (int j = 1; j < materiasCarrera.get(i).size(); j++) {
                matCar = matCar + materiasCarrera.get(i).get(j) + "  ";
            }
            matCar = matCar + "<br>";
        }

        matCar = matCar + fin;

        lblMateriasCarrera.setText(matCar);

        ArrayList<ArrayList<String>> matDocenCar = SQLDistributivo.cargarMateriasDocenteCarrera(peri.getFk_carrera());

        cedulasDocen = new ArrayList();

        for (int i = 0; i < matDocenCar.size(); i++) {
            for (int j = 2; j < matDocenCar.get(i).size(); j++) {
                matDocCar = matDocCar + matDocenCar.get(i).get(j) + "  ";

                cedulasDocen.add(matDocenCar.get(i).get(1));
            }
            matDocCar = matDocCar + "<br>";
        }

        matDocCar = matDocCar + fin;

        lblMateriasCarreraDocente.setText(matDocCar);

        //Buscamos la carrera 
        Carrera car = buscarCarrera(peri.getFk_carrera());
        //Llenamos el combo de ciclos 
        int numCiclos = car.getNum_ciclos_carrera();
        comboCiclos.removeAllItems();
        for (int i = 0; i < numCiclos; i++) {
            comboCiclos.addItem((i + 1) + "");
        }

        //Llenamos el parlelos materia
        String par = ini;

        ArrayList<ArrayList<String>> parlCar = SQLDistributivo.cargarParalelosCarrera(peri.getFk_carrera());

        for (int i = 0; i < parlCar.size(); i++) {
            for (int j = 1; j < parlCar.get(i).size(); j++) {
                par = par + parlCar.get(i).get(j) + "  ";
            }

            par = par + "<br>";
        }

        par = par + fin;

        lblParalelosCarrera.setText(par);

        //Llenamos el combo de jornadas  
        ArrayList<Carrera_Jornada> jornadasCDB = SQLCarreras.cargarJornadasCarrera(peri.getFk_carrera());

        comboJornadas.removeAllItems();

        for (int i = 0; i < jornadasCDB.size(); i++) {
            if (jornadasCDB.get(i).getFk_jornada() == 1) {
                comboJornadas.addItem("Matutina");
            }

            if (jornadasCDB.get(i).getFk_jornada() == 2) {
                comboJornadas.addItem("Vespertina");
            }

            if (jornadasCDB.get(i).getFk_jornada() == 3) {
                comboJornadas.addItem("Nocturna");
            }
        }

    }//GEN-LAST:event_comboPeriodoLectActionPerformed

    private void btnInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseClicked
        Similitudes.cambioPanel(panelCuerpo, panelInfo);
    }//GEN-LAST:event_btnInfoMouseClicked

    private void btnParalelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParalelosMouseClicked
        Similitudes.cambioPanel(panelCuerpo, panelParalelos);

    }//GEN-LAST:event_btnParalelosMouseClicked

    private void comboCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCiclosActionPerformed

        try {
            ArrayList<ArrayList<String>> parlCicloCar = SQLDistributivo.cargarParalelosCarreraCiclo(peri.getFk_carrera(),
                    Integer.parseInt(comboCiclos.getSelectedItem().toString()));

            String ini = "<html> ";
            String fin = "</html>";
            String parlCiclo = ini;

            for (int i = 0; i < parlCicloCar.size(); i++) {
                int tam = parlCicloCar.get(i).size();
                for (int j = 1; j < parlCicloCar.get(i).size() - 3; j++) {
                    parlCiclo = parlCiclo + parlCicloCar.get(i).get(j) + "  ";
                }

                String diasJdr = parlCicloCar.get(i).get(tam - 3);
                int horaIni = Integer.parseInt(parlCicloCar.get(i).get(tam - 2));
                int horaFin = Integer.parseInt(parlCicloCar.get(i).get(tam - 1));

                parlCiclo = parlCiclo + "  # horas: " + (horaFin - horaIni)
                        + "  # dias: " + numDiasClase(diasJdr) + "<br>";
            }

            parlCiclo = parlCiclo + fin;

            lblParalelosCiclo.setText(parlCiclo);
        } catch (Exception e) {
            System.out.println("Error en el accion de ciclos " + e.getMessage());
        }
    }//GEN-LAST:event_comboCiclosActionPerformed

    private void comboJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJornadasActionPerformed

        try {
            ArrayList<ArrayList<String>> parlCicloCar = SQLDistributivo.cargarParalelosCarreraCicloJorada(peri.getFk_carrera(),
                    Integer.parseInt(comboCiclos.getSelectedItem().toString()), (comboJornadas.getSelectedIndex() + 1));

            String ini = "<html> ";
            String fin = "</html>";
            String parlCicloJorn = ini;

            for (int i = 0; i < parlCicloCar.size(); i++) {
                int tam = parlCicloCar.get(i).size();
                for (int j = 1; j < parlCicloCar.get(i).size() - 3; j++) {
                    parlCicloJorn = parlCicloJorn + parlCicloCar.get(i).get(j) + "  ";
                }

                String diasJdr = parlCicloCar.get(i).get(tam - 3);
                int horaIni = Integer.parseInt(parlCicloCar.get(i).get(tam - 2));
                int horaFin = Integer.parseInt(parlCicloCar.get(i).get(tam - 1));

                parlCicloJorn = parlCicloJorn + "  # horas: " + (horaFin - horaIni)
                        + "  # dias: " + numDiasClase(diasJdr) + "<br>";

                agregarFila((horaFin - horaIni), numDiasClase(diasJdr));
            }

            parlCicloJorn = parlCicloJorn + fin;

            lblParlJornadaCiclo.setText(parlCicloJorn);
        } catch (Exception e) {
            System.out.println("Error en el accion de ciclos " + e.getMessage());
        }

    }//GEN-LAST:event_comboJornadasActionPerformed

    private void btnMasInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasInfoMouseClicked
        Similitudes.cambioPanel(panelCuerpo, panelMasInfo);
    }//GEN-LAST:event_btnMasInfoMouseClicked

    ArrayList<ArrayList<String>> docentesMatFilt = new ArrayList(); 
    
    private void btnClasificarMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClasificarMatMouseClicked

        ArrayList<ArrayList<String>> matCicloCar = SQLDistributivo.cargarMateriasCarreraCiclo(peri.getFk_carrera(),
                Integer.parseInt(comboCiclos.getSelectedItem().toString()));

        docentesMatFilt = new ArrayList();

        //Vamos a clasificar todos los docentes para que solo quede uno que va a dar esa materia  
        //Generar un random para coger una cedula random
        int numRan = 0;

        for (int i = 0; i < cedulasDocen.size(); i++) {

            numRan = (int) (Math.random() * cedulasDocen.size());

            ArrayList<ArrayList<String>> matDocen = SQLDistributivo.cargarMateriasPrefDocente(cedulasDocen.get(numRan));
            for (int j = 0; j < matDocen.size(); j++) {
                for (int k = 0; k < matCicloCar.size(); k++) {
                    if (matDocen.get(j).get(0).equals(matCicloCar.get(k).get(0))) {
                        if (!existeMatSelec(matDocen.get(j).get(0)) && !existeDocenSelec(cedulasDocen.get(i))) {
                            ArrayList<String> aux = new ArrayList();
                            aux.add(cedulasDocen.get(i));
                            aux.add(matDocen.get(j).get(0));
                            aux.add(matDocen.get(j).get(1));
                            aux.add(matDocen.get(j).get(2));
                            aux.add(matCicloCar.get(k).get(2));

                            docentesMatFilt.add(aux);
                            k = matCicloCar.size();
                        }

                    }
                }
            }

        }

        for (int i = 0; i < docentesMatFilt.size(); i++) {

            modeloTabla.addRow(docentesMatFilt.get(i).toArray());
        }

    }//GEN-LAST:event_btnClasificarMatMouseClicked

    public boolean existeMatSelec(String fk_mat) {
        boolean existe = false;
        for (int i = 0; i < docentesMatFilt.size(); i++) {
            if (docentesMatFilt.get(i).get(1).equals(fk_mat)) {
                existe = true;
            }
        }
        return existe;
    }

    public boolean existeDocenSelec(String cedula) {
        boolean existe = false;
        for (int i = 0; i < docentesMatFilt.size(); i++) {
            if (docentesMatFilt.get(i).get(0).equals(cedula)) {
                existe = true;
            }
        }
        return existe;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributivoVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributivoVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributivoVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributivoVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistributivoVtn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClasificarMat;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnMasInfo;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnParalelos;
    private javax.swing.JComboBox<String> comboCiclos;
    private javax.swing.JComboBox<String> comboJornadas;
    private javax.swing.JComboBox<String> comboPeriodoLect;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblMateriasCarrera;
    private javax.swing.JLabel lblMateriasCarreraDocente;
    private javax.swing.JLabel lblNumDias;
    private javax.swing.JLabel lblNumDias1;
    private javax.swing.JLabel lblNumDiasSinFS;
    private javax.swing.JLabel lblNumDiasSinFS2;
    private javax.swing.JLabel lblNumDiasSinFS3;
    private javax.swing.JLabel lblNumDiasSinFS4;
    private javax.swing.JLabel lblNumDiasSinFS5;
    private javax.swing.JLabel lblNumDiasSinFS6;
    private javax.swing.JLabel lblNumDiasSinFS7;
    private javax.swing.JLabel lblNumSemanas;
    private javax.swing.JLabel lblNumSemanas2;
    private javax.swing.JLabel lblParalelosCarrera;
    private javax.swing.JLabel lblParalelosCiclo;
    private javax.swing.JLabel lblParlJornadaCiclo;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelHeader1;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelMasInfo;
    private javax.swing.JPanel panelParalelos;
    private javax.swing.JTable tblInfoMat;
    // End of variables declaration//GEN-END:variables
}
