/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Administrador;

import BaseDatos.Conexion_Consultas;
import BaseDatos.SQLCarreras;
import BaseDatos.SQLPeriodoLectivo;
import Clases.Carrera;
import Clases.Periodo_Lectivo;
import Clases.Validaciones;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Johnny
 */
public class PeriodoLectivoVtn extends javax.swing.JFrame {

    //Creamos nuestro modelo de tabla 
    DefaultTableModel modeloTabla;
    //Le damos su titulo 
    String tituloTabla[] = {"id", "Fecha Inicio", "Fecha Fin", "Año", "Carrera"};
    String datos[][] = {};

    //Para mover la ventana 
    int mousex;
    int mousey;

    //Para saber si los botones estan avilitados  
    boolean btnAvilitados = false;

    //Guardamos la posicion de la fila que seleciono 
    int filaSelecionada;
    //Guardamos la posicion de la fila selecionada al momento de clickear en editar
    int filaEditar;

    //Variable para saber si estoy editando o no  
    boolean editando = false;

    //Creamos nuestra variable para validar 
    Validaciones valido = new Validaciones();

    //Para guardar periodos lectivo  
    ArrayList<Periodo_Lectivo> periodos = new ArrayList();
    
    //Aqui guardamos las carreras de un isntituto  
    ArrayList<Carrera> carrerasDB = new ArrayList(); 

    public PeriodoLectivoVtn() {
        initComponents();

        //Abrimos la conexion 
        Conexion_Consultas.conectar();
        
        
        actualizarComboCarrera();

        //Deshabilitamos los botones  
        btnEliminar.setEnabled(false);

        //Inicializamos nuestra tabla 
        modeloTabla = new DefaultTableModel(datos, tituloTabla);
        actualizarTblPeriodoLectivo();
        
        
         
        //Pasamos el modelo a la tabla  
        tblPeriodoLectivo.setModel(modeloTabla);

        //Modificamos el tamaño de las columnas
        TableColumnModel columModel = tblPeriodoLectivo.getColumnModel();

        Similitudes.ocultarID(tblPeriodoLectivo);

        columModel.getColumn(1).setPreferredWidth(100);
        columModel.getColumn(2).setPreferredWidth(100);
        columModel.getColumn(3).setPreferredWidth(50);
        columModel.getColumn(4).setPreferredWidth(220);

        //Modificamos el header nuestra tabla  
        Similitudes.tituloTbls(tblPeriodoLectivo);

        //Ocultamos todos los errores 
        lblErrorFechaInicio.setVisible(false);
        lblErrorFechaFin.setVisible(false);
        lblErrorAnio.setVisible(false);
        lblFondo.setVisible(false);
    }
    
    private void actualizarComboCarrera(){
        carrerasDB = SQLCarreras.cargarCarrerasDB(true); 
        comboCarrera.removeAllItems();
        
        for (int i = 0; i < carrerasDB.size(); i++) {
            comboCarrera.addItem(carrerasDB.get(i).getNombre_Carrera());
        }
    }

    private void actualizarTblPeriodoLectivo() {
        modeloTabla.setRowCount(0); 
        
        if (!SQLPeriodoLectivo.cargarPeriodosLectivos(true).isEmpty()) {
            periodos = SQLPeriodoLectivo.cargarPeriodosLectivos(true);

            for (int i = 0; i < periodos.size(); i++) {

                if (periodos.get(i).isPer_lect_activo()) {
                    Object[] valores = {periodos.get(i).getId_per_lect(),
                        periodos.get(i).getFecha_ini_per_lect(),
                        periodos.get(i).getFecha_fin_epr_lect(),
                        periodos.get(i).getAnio_per_lect(),
                        nomCarrera(periodos.get(i).getFk_carrera())};

                    modeloTabla.addRow(valores);
                }
            }
        }
    }
    
    private String nomCarrera(int fk_carrera){
        String nombre = "";
        for (int i = 0; i < carrerasDB.size(); i++) {
            if (carrerasDB.get(i).getId_carrera() == fk_carrera) {
                nombre  = carrerasDB.get(i).getNombre_Carrera();
                break; 
            }
        }
        return nombre; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuerpo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeriodoLectivo = new JTable(){
            @Override 
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false; 
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblErrorAnio = new javax.swing.JLabel();
        lblErrorFechaInicio = new javax.swing.JLabel();
        lblErrorFechaFin = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        anio = new com.toedter.calendar.JYearChooser();
        lblFondo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboCarrera = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCuerpo.setBackground(new java.awt.Color(231, 235, 230));
        panelCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(231, 235, 230));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblPeriodoLectivo.setBackground(new java.awt.Color(231, 235, 230));
        tblPeriodoLectivo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblPeriodoLectivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Fecha Inicio", "Fecha Fin", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPeriodoLectivo.setOpaque(false);
        tblPeriodoLectivo.setSelectionBackground(new java.awt.Color(21, 89, 110));
        tblPeriodoLectivo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPeriodoLectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeriodoLectivoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeriodoLectivo);

        panelCuerpo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 450, 280));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 89, 110));
        jLabel1.setText("Fecha Inicio:");
        panelCuerpo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 89, 110));
        jLabel3.setText("Fecha Fin:");
        panelCuerpo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 89, 110));
        jLabel4.setText("Carrera:");
        panelCuerpo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(99, 144, 158));
        btnGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        panelCuerpo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 110, -1));

        btnEliminar.setBackground(new java.awt.Color(118, 125, 127));
        btnEliminar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setOpaque(true);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        panelCuerpo.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 110, -1));

        lblErrorAnio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblErrorAnio.setForeground(new java.awt.Color(115, 30, 16));
        lblErrorAnio.setText("Ingrese un año valido. ");
        panelCuerpo.add(lblErrorAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 160, 20));

        lblErrorFechaInicio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblErrorFechaInicio.setForeground(new java.awt.Color(115, 30, 16));
        lblErrorFechaInicio.setText("Ingrese una fecha correcta.");
        panelCuerpo.add(lblErrorFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 180, 20));

        lblErrorFechaFin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblErrorFechaFin.setForeground(new java.awt.Color(115, 30, 16));
        lblErrorFechaFin.setText("Ingrese una fecha correcta.");
        panelCuerpo.add(lblErrorFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 180, 20));

        fechaInicio.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        fechaInicio.setMaxSelectableDate(new java.util.Date(253370786461000L));
        fechaInicio.setMinSelectableDate(new java.util.Date(1483250461000L));
        fechaInicio.setOpaque(false);
        panelCuerpo.add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, 30));

        fechaFin.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        panelCuerpo.add(fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 210, 30));
        panelCuerpo.add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 80, 30));

        lblFondo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(115, 30, 16));
        lblFondo.setText("Ya registro este periodo lectivo.");
        panelCuerpo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 220, 20));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 89, 110));
        jLabel7.setText("Año:");
        panelCuerpo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        comboCarrera.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        comboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelCuerpo.add(comboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 320, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/FondoLapiz3.png"))); // NOI18N
        panelCuerpo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        getContentPane().add(panelCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 810, 460));

        panelHeader.setBackground(new java.awt.Color(9, 28, 32));
        panelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelHeaderMouseDragged(evt);
            }
        });
        panelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelHeaderMousePressed(evt);
            }
        });
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Login_26px_1.png"))); // NOI18N
        btnMenu.setToolTipText("Volver al menu");
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusPainted(false);
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMenu.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/icons8_Login_26px_2.png"))); // NOI18N
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        panelHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingresar Periodo Lectivo");
        panelHeader.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Administracion/BanerKay.png"))); // NOI18N
        jLabel11.setToolTipText("");
        panelHeader.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPeriodoLectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriodoLectivoMouseClicked

        try {

            filaSelecionada = tblPeriodoLectivo.getSelectedRow();

            //Activamos nuestros botones
            if (filaSelecionada >= 0) {
                btnAvilitados = true;

                //Modificamos los botones, para que pueda ser usados
                //Cambio sus colores para que se ve mejor que estan visibles
                btnEliminar.setBackground(new Color(99, 144, 158));

                btnEliminar.setEnabled(true);
            }

        } catch (IndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }

    }//GEN-LAST:event_tblPeriodoLectivoMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        boolean guardar = true;

        int id_periodo = 0;

        if (periodos.size() > 0) {
            id_periodo = periodos.get(periodos.size() - 1).getId_per_lect();
        }
        id_periodo++;

        //String fechaIni =  this.fechaInicio.getDateFormatString(); 
        String fechaIni = new SimpleDateFormat("dd/MM/yyyy").format(this.fechaInicio.getDate());

        //String fechaFin = this.fechaFin.getDateFormatString(); 
        String fechaFin = new SimpleDateFormat("dd/MM/yyyy").format(this.fechaFin.getDate());;

        String anio = String.valueOf(this.anio.getValue());
        if (!valido.esAnio(anio)) {
            lblErrorAnio.setVisible(true);
            guardar = false;
        }

        int pos = comboCarrera.getSelectedIndex();
        int fk_carrera = carrerasDB.get(pos).getId_carrera();

        for (int i = 0; i < periodos.size(); i++) {
            if (periodos.get(i).getFecha_ini_per_lect().equals(fechaIni)
                    && periodos.get(i).getFecha_fin_epr_lect().equals(fechaFin)
                    && periodos.get(i).getAnio_per_lect().equals(anio)) {
                guardar = false;
                lblFondo.setVisible(true);
                break;
            }
        }

        System.out.println(anio);

        //Si no encontraron ningun error se guarda
        if (guardar) {

            if (!editando) {

                Periodo_Lectivo perio = new Periodo_Lectivo();
                perio.setId_per_lect(id_periodo);
                perio.setFecha_ini_per_lect(fechaIni);
                perio.setFecha_fin_epr_lect(fechaFin);
                perio.setAnio_per_lect(anio);
                perio.setPer_lect_activo(true);
                perio.setFk_carrera(fk_carrera); 
                

                SQLPeriodoLectivo.insertarPeriodoLectio(perio);

            }

            if (editando) {
                //Seteamos los valores en la posicion que dimos click al editar
                modeloTabla.setValueAt(fechaInicio, filaEditar, 1);
                modeloTabla.setValueAt(fechaFin, filaEditar, 2);
                modeloTabla.setValueAt(anio, filaEditar, 3);

                Periodo_Lectivo perio = new Periodo_Lectivo();
                perio.setId_per_lect(Integer.parseInt(tblPeriodoLectivo.getValueAt(filaEditar, 0).toString()));
                perio.setFecha_ini_per_lect(fechaIni);
                perio.setFecha_fin_epr_lect(fechaFin);
                perio.setAnio_per_lect(anio);
                perio.setFk_carrera(fk_carrera); 

                SQLPeriodoLectivo.editarPeriodoLectivo(perio);

                editando = false;
            }

            //Cambiamos el estado de los botones nuevamente
            btnEliminar.setBackground(new Color(118, 125, 127));

            btnEliminar.setEnabled(false);

            //Ocultamos todos los errores
            lblErrorFechaInicio.setVisible(false);
            lblErrorFechaFin.setVisible(false);
            lblErrorAnio.setVisible(false);
            
            actualizarTblPeriodoLectivo();

        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(21, 89, 110));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(99, 144, 158));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked

        try {
            //Eliminamos la fila que este selecionada
            if (filaSelecionada >= 0 && btnAvilitados) {
                SQLPeriodoLectivo.eliminarPeriodoLectivo(Integer.parseInt(tblPeriodoLectivo.getValueAt(filaSelecionada, 0).toString()));

                modeloTabla.removeRow(filaSelecionada);
            }

            //Cambiamos los botones a inactivos
            btnEliminar.setBackground(new Color(118, 125, 127));

            btnEliminar.setEnabled(false);

            btnAvilitados = false;
            editando = false;
        } catch (IndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        if (btnAvilitados) {
            btnEliminar.setBackground(new Color(21, 89, 110));
        }
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        if (btnAvilitados) {
            btnEliminar.setBackground(new Color(99, 144, 158));
        }
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        AdministracionVtn admin = new AdministracionVtn();
        admin.setVisible(true);
        this.dispose();

        Conexion_Consultas.cerrarConexion();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void panelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_panelHeaderMouseDragged

    private void panelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_panelHeaderMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeriodoLectivoVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeriodoLectivoVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeriodoLectivoVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeriodoLectivoVtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeriodoLectivoVtn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser anio;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> comboCarrera;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorAnio;
    private javax.swing.JLabel lblErrorFechaFin;
    private javax.swing.JLabel lblErrorFechaInicio;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tblPeriodoLectivo;
    // End of variables declaration//GEN-END:variables

}
