/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.LoginRegistro;

import BaseDatos.Conexion_Consultas;
import Clases.Docente;
import Clases.Estudiante;
import Interfaz.Administrador.AdministracionVtn;
import Interfaz.Kayrana.App;
import Validacion.Validacion;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Johnny
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private String usuario;
    private static Docente userDocente;
    private static Estudiante userEstudiante;
    private static boolean registrado = true;
    static final int limite = 10;
    Validacion validar = new Validacion();
    
    //Array de cedulas de admins  
    String adminCedula [] = {"0107390270", "0105813877", "0106755127"};
    
    //Para mover la pantalla  
    int mouseX; 
    int mousey; 

    public Login() {
        initComponents();
        //Icono de la palicacion 
        try {
            setIconImage(new ImageIcon(getClass().getResource("/img/LogoKayranaCircularV.1.png")).getImage());
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
        Conexion_Consultas.conectar();
        txtUsuarioNoReg.setVisible(false);
        lblError.setVisible(false);

        //btnEntrar.setFocusable(true); 
    }

    public void setUserDocente(Docente docen) {
        //System.out.println(docen);
        this.userDocente = docen;
    }

    public void setUserEstudiante(Estudiante est) {
        this.userEstudiante = est;
    }

    public boolean autenticar() {
        boolean encontrado = false;
        String cedula = txtUsuario.getText();
        String contrasena = String.valueOf(txtPassword.getPassword());
        usuario = Conexion_Consultas.ingreso(cedula, contrasena);

        System.out.println(usuario);
        System.out.println(userDocente);
        System.out.println(userEstudiante);

        if (usuario.equals("")) {
            txtUsuarioNoReg.setVisible(true);
            encontrado = false;
        }
        if (userDocente != null) {
            if (userDocente.getContrasenaUsuario().equals(contrasena)) {
                System.out.println("Bienvenido " + usuario);
                encontrado = true;
            } else {
                lblError.setVisible(true);
            }
        } else if (userEstudiante != null) {
            if (userEstudiante.getContrasenaUsuario().equals(contrasena)) {
                System.out.println("Bienvenido " + usuario);
                encontrado = true;
            } else {
                lblError.setVisible(true);
            }
        } else {
            System.out.println("No entramos en ninguno de los tipo de usuario");
        }
        return encontrado;
    }

    public static void registrado(boolean registrado) {
        Login.registrado = registrado;
    }

    public void entrarApp() {
        String cedula = txtUsuario.getText(); 
        boolean esAdmin = false; 
        for (int i = 0; i < 3; i++) {
            if(adminCedula[i].equals(cedula)){
                esAdmin = true;
                break; 
            }
        }
        
        if (esAdmin && String.valueOf(txtPassword.getPassword()).equals("soyadmin")) {
            AdministracionVtn admin = new AdministracionVtn();
            admin.setVisible(true);
            this.dispose();
        }

        if (autenticar()) {
            App app = new App();
            if (userDocente != null) {
                app.setUserDocente(userDocente);
            }

            if (userEstudiante != null) {
                app.setUserEstudiante(userEstudiante);
            }
            app.bienvenida(usuario);
            app.setVisible(true);
            //Borramos los datos de aqui 
            userDocente = null;
            userEstudiante = null;
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtUsuarioNoReg = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/EntrarLRojas.jpg"))); // NOI18N
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setFocusPainted(false);
        btnEntrar.setOpaque(false);
        btnEntrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/Entrar.jpg"))); // NOI18N
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEntrarKeyPressed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        btnRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/registrase1.jpg"))); // NOI18N
        btnRegistrarse.setBorder(null);
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.setFocusPainted(false);
        btnRegistrarse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/registrase2.jpg"))); // NOI18N
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 46, 53));
        jLabel3.setText(" ¿No tiene una cuenta?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 170, -1));

        lblError.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(173, 46, 25));
        lblError.setText("Usuario o contraseña incorrectos");
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/icons8_Delete_26px_2.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/icons8_Close_Window_26px_4.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));

        txtUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtUsuario.setOpaque(false);
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 230, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPassword.setOpaque(false);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 230, -1));

        txtUsuarioNoReg.setColumns(2);
        txtUsuarioNoReg.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtUsuarioNoReg.setForeground(new java.awt.Color(173, 46, 25));
        txtUsuarioNoReg.setRows(5);
        txtUsuarioNoReg.setText("Usuario no registrado");
        txtUsuarioNoReg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtUsuarioNoReg.setFocusable(false);
        txtUsuarioNoReg.setOpaque(false);
        getContentPane().add(txtUsuarioNoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 210, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 46, 53));
        jLabel1.setText("Contraseña:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 180, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 46, 53));
        jLabel2.setText("Cédula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 150, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 230, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 230, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/icons8_Add_User_Group_Woman_Man_48px.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 50, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/icons8_Key_48px.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 50, -1));

        jLabel6.setBackground(new java.awt.Color(201, 211, 200));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/logoPequeño.png"))); // NOI18N
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 310, 80));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login/Login1.0.jpg"))); // NOI18N
        lblFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblFondoMouseDragged(evt);
            }
        });
        lblFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFondoMousePressed(evt);
            }
        });
        lblFondo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblFondoKeyPressed(evt);
            }
        });
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        entrarApp();
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        Registro registrar = new Registro();
        registrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtUsuario != null) {
                entrarApp();
            }
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        if (validar.ValidaCedula(txtUsuario.getText())) {
            txtPassword.setEnabled(true);
            System.out.println("Cedula Correcta");
        } else {
            System.out.println("Cedula no valida");
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void btnEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntrarKeyPressed
        entrarApp();
    }//GEN-LAST:event_btnEntrarKeyPressed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        if (txtUsuario.getText().length() == limite) {
            evt.consume();
        } else {
            //txtPassword.setEnabled(false);
            txtPassword.setText("");
            char caracter = evt.getKeyChar();
            // Verificar si la tecla pulsada no es un digito
            if (((caracter < '0') || (caracter > '9')) && (caracter != '\b'  )) { //corresponde a BACK_SPACE 
                System.out.println("Debe ingresar solo caracteres numericos");
                evt.consume(); // ignorar el evento de teclado   
            }
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void lblFondoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblFondoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtUsuario != null) {
                entrarApp();
            }
        }
    }//GEN-LAST:event_lblFondoKeyPressed

    private void lblFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoMousePressed
        mouseX = evt.getX();
        mousey = evt.getY(); 
    }//GEN-LAST:event_lblFondoMousePressed

    private void lblFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoMouseDragged
        int x = evt.getXOnScreen(); 
        int y = evt.getYOnScreen();
        
        this.setLocation(x - mouseX, y - mousey); 
    }//GEN-LAST:event_lblFondoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextArea txtUsuarioNoReg;
    // End of variables declaration//GEN-END:variables
}
