/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.LoginRegistro;

import BaseDatos.Conexion_Consultas;
import Validacion.Validacion;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Johnny
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    static ArrayList<String> cedulas = new ArrayList<>();
    private String cedula = "000";
    static final int limite = 10;
    Validacion validar = new Validacion();
    
    //Para mover la pantalla  
    int mouseX; 
    int mouseY; 

    public Registro() {
        initComponents();

        //Conexion_Consultas.conectar();
        //Icono de la palicacion 
        try {
            setIconImage(new ImageIcon(getClass().getResource("../img/LogoKayranaCircularV.1.png")).getImage());
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }

        cedulas = Conexion_Consultas.acceso();
        lblErrorNombreDoc.setVisible(false);
        lblErrorRegistro.setVisible(false);

    }

    public String existeUsuario(String cedula) {
        String usuario = Conexion_Consultas.ingreso(cedula, "--");
        return usuario;
    }

    public static boolean verificar_acceso(String parametro) {
        int i = 0;
        boolean es_docente = false;

        while (!es_docente && i < cedulas.size()) {
            if (cedulas.get(i).equals(parametro)) {
                es_docente = true;
            }
            i++;
        }

        return es_docente;
    }

    public void registrarse() {
        
        cedula = txtCedula.getText(); 
        
        
        if (existeUsuario(txtCedula.getText()).equals("")) { 

            if (validar.ValidaCedula(txtCedula.getText())) {
                System.out.println("Cedula correcta");
                if (verificar_acceso(txtCedula.getText())) {
                    RegistroDocente registroDocente = new RegistroDocente();
                    registroDocente.cedulaDocente(cedula); 
                    registroDocente.setVisible(true);
                } else {
                    RegistroEstudiante registroEstudiante = new RegistroEstudiante();
                    registroEstudiante.cedulaEstudiante(cedula); 
                    registroEstudiante.setVisible(true);
                }
                //Conexion_Consultas.cerrarConexion();
                this.dispose();
            } else {
                System.out.println("Cedula incorrecta");
            }
        }else{
            lblErrorRegistro.setVisible(true); 
        }
        /*
        if (existeUsuario(txtCedula.getText()).equals("")) {
            
            if (verificar_acceso(cedula)) {
                RegistroDocente registroDocente = new RegistroDocente();
                registroDocente.cedulaDocente(cedula);
                registroDocente.setVisible(true);
            } else {
                RegistroEstudiante registroEstudiante = new RegistroEstudiante();
                registroEstudiante.cedulaEstudiante(cedula);
                registroEstudiante.setVisible(true);
            }
            //Conexion_Consultas.cerrarConexion();
            this.dispose();

        } else {
            lblErrorRegistro.setVisible(true);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDocente = new javax.swing.JPanel();
        lblDocente = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtCedula = new javax.swing.JTextField();
        btnRegistrarme = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        lblErrorNombreDoc = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblErrorRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 150));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDocente.setBackground(new java.awt.Color(231, 235, 230));
        panelDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelDocenteKeyPressed(evt);
            }
        });
        panelDocente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDocente.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        lblDocente.setForeground(new java.awt.Color(163, 162, 157));
        lblDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDocente.setText("I N G R E S E   S U   C E D U L A");
        lblDocente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblDocenteMouseDragged(evt);
            }
        });
        lblDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDocenteMousePressed(evt);
            }
        });
        panelDocente.add(lblDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 300, 40));
        panelDocente.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 10));

        txtCedula.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtCedula.setOpaque(false);
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        panelDocente.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 220, -1));

        btnRegistrarme.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnRegistrarme.setForeground(new java.awt.Color(255, 160, 0));
        btnRegistrarme.setText("R E G I S T R A R M E");
        btnRegistrarme.setBorder(null);
        btnRegistrarme.setBorderPainted(false);
        btnRegistrarme.setContentAreaFilled(false);
        btnRegistrarme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarme.setFocusPainted(false);
        btnRegistrarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarmeMouseClicked(evt);
            }
        });
        panelDocente.add(btnRegistrarme, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));
        panelDocente.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, 10));

        lblErrorNombreDoc.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblErrorNombreDoc.setForeground(new java.awt.Color(173, 46, 25));
        lblErrorNombreDoc.setText("Solo debe ingresar numeros.");
        panelDocente.add(lblErrorNombreDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Registro/icons8_Cancel_26px.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Registro/icons8_Cancel_26px_1.png"))); // NOI18N
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        panelDocente.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 30, 30));

        lblErrorRegistro.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblErrorRegistro.setForeground(new java.awt.Color(173, 46, 25));
        lblErrorRegistro.setText("Usuario ya registrado.");
        panelDocente.add(lblErrorRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        getContentPane().add(panelDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarmeMouseClicked
        registrarse();
    }//GEN-LAST:event_btnRegistrarmeMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked

        Login log = new Login();
        log.setVisible(true);
        this.dispose();

        Conexion_Consultas.cerrarConexion();

    }//GEN-LAST:event_btnCancelarMouseClicked

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            registrarse();
        }
    }//GEN-LAST:event_txtCedulaKeyPressed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        
        if (txtCedula.getText().length() == limite) {
            //txtPassword.setEnabled(true);
            evt.consume();
        } else {
            char caracter = evt.getKeyChar();
            // Verificar si la tecla pulsada no es un digito
            if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' )) { // corresponde a BACK_SPACE 
                System.out.println("Debe ingresar solo caracteres numericos");
                evt.consume(); // ignorar el evento de teclado   
            }
        }
       
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void panelDocenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelDocenteKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            registrarse();
        } 
    }//GEN-LAST:event_panelDocenteKeyPressed

    private void lblDocenteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDocenteMousePressed
        mouseX = evt.getX(); 
        mouseY = evt.getY();
    }//GEN-LAST:event_lblDocenteMousePressed

    private void lblDocenteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDocenteMouseDragged
        int x = evt.getXOnScreen(); 
        int y = evt.getYOnScreen();
        
        this.setLocation(x - mouseX, y - mouseY); 
    }//GEN-LAST:event_lblDocenteMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarme;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblErrorNombreDoc;
    private javax.swing.JLabel lblErrorRegistro;
    private javax.swing.JPanel panelDocente;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
