/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DistributivoVJohnny.vista;

import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author Usuario
 */
public class PnlDocentes extends javax.swing.JPanel {

    /**
     * Creates new form pnlDocentes
     */
    public PnlDocentes() {
        initComponents();
    }

    public JComboBox<String> getCbDocente() {
        return cbDocente;
    }

    public JTable getTblDocentes() {
        return tblDocentes;
    }

    public JTable getTblMaterias() {
        return tblMaterias;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocentes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbDocente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cedula", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tblDocentes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 660, 200));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Lista de todos los docentes que peretenecen al periodo lectivo de esta carrera:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 30));

        cbDocente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 270, 30));

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Materia", "Ciclo", "Horas/Semana"
            }
        ));
        jScrollPane2.setViewportView(tblMaterias);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 370, 120));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Elija el docente para ver sus materias:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 280, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDocente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDocentes;
    private javax.swing.JTable tblMaterias;
    // End of variables declaration//GEN-END:variables
}
