/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DistributivoVJohnny.vista;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Usuario
 */
public class PnlInformacion extends javax.swing.JPanel {

    /** Creates new form PnlInformacion */
    public PnlInformacion() {
        initComponents();
    }

    public JButton getBtnSeleccionar() {
        return btnSeleccionar;
    }

    public JButton getBtnSortear() {
        return btnSortear;
    }

    public JTable getTblDocentesSelecionados() {
        return tblDocentesSelecionados;
    }

    public JTable getTblHorarioOrdenado() {
        return tblHorarioOrdenado;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarioOrdenado = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDocentesSelecionados = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        btnSortear = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("HORA COMPLETO");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 700, 40));

        tblHorarioOrdenado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHorarioOrdenado);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 680, 200));

        tblDocentesSelecionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDocentesSelecionados);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 580, 160));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("<html>Docentes del Instituo:</html>");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 50));

        btnSeleccionar.setText("Seleccionar");
        add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        btnSortear.setText("Sortear");
        add(btnSortear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnSortear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDocentesSelecionados;
    private javax.swing.JTable tblHorarioOrdenado;
    // End of variables declaration//GEN-END:variables

}
