/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DistributivoVJohnny.vista;

import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author Usuario
 */
public class PnlParalelos extends javax.swing.JPanel {

    /**
     * Creates new form pnlParalelos
     */
    public PnlParalelos() {
        initComponents();
    }

    public JComboBox<String> getCbParalelo() {
        return cbParalelo;
    }

    public JTable getTblJornadas() {
        return tblJornadas;
    }

    public JTable getTblParalelos() {
        return tblParalelos;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbParalelo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParalelos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJornadas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbParalelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbParalelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbParalelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 270, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Todos los paralelos que tiene este periodo lectivo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 30));

        tblParalelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Ciclo"
            }
        ));
        jScrollPane1.setViewportView(tblParalelos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 660, 230));

        tblJornadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Jornada"
            }
        ));
        jScrollPane2.setViewportView(tblJornadas);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 380, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Elija el paralelo para ver sus jornadas:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 280, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbParalelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblJornadas;
    private javax.swing.JTable tblParalelos;
    // End of variables declaration//GEN-END:variables
}
